name: Node Continuous Integration 
on: 
  pull_request: 
  push: 

jobs: 
  test_pull_request: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1

